export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_FILTERED_PROFILES = 'GET_FILTERED_PROFILES';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const FILTER_PROFILES = 'FILTER_PROFILES';
export const GET_SUBJECTS = 'GET_SUBJECTS';
export const SUBJECTS_LOADING = 'SUBJECTS_LOADING';
export const DELETE_SUBJECTS = 'DELETE_SUBJECTS';

// Possible UI action types
export const SHOW_POPUP = 'SHOW_POPUP';