const classList = {
 	majors: [ "Biology",
		"Chemistry",
		"Civil Engineering",
		"Communication",
		"Computer Science",
		"Economics",
		"Electrical Engineering",
		"Elementary Education",
		"English",
		"Environmental Ethics & Policy",
		"Environmental Science",
		"Finance",
		"French Studies",
		"General Studies",
		"German Studies",
		"History",
		"Marketing",
		"Mathematics",
		"Mechanical Engineering",
		"Music",
		"Nursing",
		"Operations & Technology Management",
		"Organizational Communication",
		"Philosophy",
		"Physics",
		"Political Science",
		"Phycology",
		"Secondary Education",
		"Social Work",
		"Sociology",
		"Sociology/Criminology Concentration",
		"Theatre",
		"Theology",
 	],
 	minors: ["Biology",
		"Business Administration",
		"Catholic Studies",
		"Chemistry",
		"Communication",
		"Computer Engineering",
		"Computer Science",
		"Economics",
		"Education",
		"English",
		"Entrepreneurship & Innovation Management",
		"Environmental Policy",
		"Environmental Science",
		"Fine Arts",
		"French",
		"Gender & Woman's Studies",
		"German",
		"Global Business",
		"Hellenic Studies",
		"History",
		"Mathematics",
		"Music",
		"Neuroscience",
		"Philosophy",
		"Physics",
		"Political Science",
		"Psychology",
		"Social Justice",
		"Sociology",
		"Spanish",
		"Sustainability",
		"Theatre",
		"Theology",
	]
 }; 

 export default {classList};


