export const profileOptions = [
    { label: '', value: 0},
]

export const studentMajorsOptions = [
    { label: 'Biology', value: 'Biology' },
    { label: 'Business Administration', value: 'Business Administration' },
    { label: 'Catholic Studies', value: '' },
    { label: 'Chemistry', value: '' },
    { label: 'Communication', value: '' },
    { label: 'Computer Science', value: '' },
    { label: 'Economics', value: '' },
    { label: 'Education', value: '' },
    { label: 'English', value: '' },
    { label: 'Entrepreneurship & Innovation Management', value: '' },
    { label: 'Environmental Policy', value: '' },
    { label: 'Fine Arts', value: '' },
    { label: 'French', value: '' },
    { label: `Gender & Woman's Studies`, value: '' },
    { label: 'German', value: 'German' },
    { label: 'Global Business', value: '' },
    { label: 'Hellenic Studies', value: '' },
    { label: 'History', value: '' },
    { label: 'Mathematics', value: '' },
    { label: 'Music', value: '' },
    { label: 'Neuroscience', value: '' },
    { label: 'Philosophy', value: '' },
    { label: 'Physics', value: '' },
    { label: 'Political Science', value: '' },
    { label: 'Psychology', value: '' },
    { label: 'Social Justice', value: '' },
    { label: 'Sociology', value: '' },
    { label: 'Spanish', value: '' },
    { label: 'Sustainability', value: '' },
    { label: 'Theatre', value: '' },
    { label: 'Theology', value: 'Theology' },
]

const studentMinorOptions = [
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
    { label: '', value: '' },
]